### ISSUE TITLE
Data extension??

### ISSUE THREAD

**Issue by edwardcho** [JeongHyunJin/Pix2PixHD#1]
Hello sir.
I have interesting on image to image translation, want to try your network.
I check your network conditions. 
If i have another image format (png, jpg), can i try to train your code??

Thank you.
Edward cho.

**Comment by JeongHyunJin** [comment]
Hello Edward cho,

First of all, thank you for your interest in my code.
I recommend that you convert the extension of your data from (png, jpg) to (tiff or npy).
Because (png, jpg) only have integer values ​​between 0 and 255, they are not suitable for scientific data processing.

Or I suggest that you use the code from the link below:
https://github.com/NoelShin/Pix2PixHD

**Comment by edwardcho** [comment]
Hello JeongHyunJin

Thank you for your response quickly.

Thanks,
